title: YA-Hwang 기술 블로그
description: 데이터 분석을 위한 포트폴리오
permalink: 'posts/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yahwang.tk" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Seoul # 지역 시간 설정

# Author Settings
author: YA-Hwang # add your name
author-img: yahwang_logo.png # add your photo
about-author: Yes to Ambition! # add description
facebook: # add your Facebook handle
github: yahwang # add your Github handle
linkedin: # add your Linkedin handle
email: ts.yahwang@gmail.com # add your Email address
codesignal: https://app.codesignal.com/profile/yahwang
dockerhub: https://hub.docker.com/u/yahwang
# Disqus
discus-identifier: yahwang # add your discus identifier

sass:
  sass_dir: _sass
  style: compressed

# Build Settings
livereload: true

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-feed

# pagination settings
paginate: 10
paginate_path: "/posts/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Search settings
tipue_search:
  include:
    pages: false
    collections: []
  exclude:
    files: [search.html, index.html, tags.html]
    categories: []
    tags: []
