title: YaHwang 기술 블로그
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Seoul # 지역 시간 설정

# Author Settings
author: 황 태 식 # add your name
author-img: yahwang_logo.png # add your photo
about-author: Be Ambitious! # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: yahwang # add your Github handle
linkedin: # add your Linkedin handle
googledrive: 
dropbox: https://www.dropbox.com/sh/h8vq5tnmur3922n/AAAK4lgPY7rgkot60WwSksfWa?dl=0
email: hts911kr@gmail.com # add your Email address

# Disqus
discus-identifier: YaHwang # add your discus identifier

sass:
  sass_dir: _sass
  style: compressed

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
kramdown:
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
